### PR TITLE
support Python 3.10

### PR DESCRIPTION
**Pull request by spinenkoia**

### CODE REVIEW

**Comment by spinenkoia** [comment]
task #146 fix

**Comment by aamalev** [comment]
Thanx

**Comment by spinenkoia** [comment]
@aamalev  and can I ask you to release a minor version, so as not to collect from the source code?

**Comment by aamalev** [comment]
> @aamalev and can I ask you to release a minor version, so as not to collect from the source code?

https://github.com/aamalev/aiohttp_apiset/releases/tag/0.9.15

**Comment by spinenkoia** [comment]
> > @aamalev and can I ask you to release a minor version, so as not to collect from the source code?
> 
> https://github.com/aamalev/aiohttp_apiset/releases/tag/0.9.15

thank you very much

**Pull request merged**
